### ISSUE TITLE
Swap can make proxy invalid

### ISSUE THREAD

**Issue by kelbon** [mingxwa/my-stl#4]
https://github.com/mingxwa/my-stl/blob/594ed49b6dab6389ee0d009e6193570a97f8524e/main/p0957/proxy.h#L426

0. Move can throw `proxy(proxy&& rhs) noexcept(HasNothrowMoveConstructor)`
1.  Your swap realization:
```C++
 if (rhs.meta_ != nullptr) {
      proxy temp = move(*this);
      new(this) proxy(move(rhs));
      new(&rhs) proxy(move(temp));
```
3. Why your move calls destructor? 
4. After moving into `temp` you have called destructor, but `meta` is not nullptr, so if new(this) ... throws exception, then your value is invalid, it cannot even call destructor after it.
5. Why your move (and all other ctors/ etc) calls destructor...?

**Comment by mingxwa** [comment]
> Why your move calls destructor?

It's by design and could probably be eliminated with P1144.

> After moving into temp you have called destructor, but meta is not nullptr

`meta_` will become nullptr after moving `*this` to `temp`.

**Comment by kelbon** [comment]
> `meta_` will become nullptr after moving `*this` to `temp`.
Okay sorry...
But its still not a strong exception guarantee how in draft was written, yes?
Can you explain why design is not value semantic oriented? Because it is main problem of virtual functions - inheriting and non-value semantic, there are boost type erasure or my AnyAny lib (here, on github)

**Comment by mingxwa** [comment]
> But its still not a strong exception guarantee how in draft was written, yes?

No, it's not. None of the standard types have strong exception safety guarantee on `swap`. See the wording in 5.3.3.4, [P0957R6](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p0957r6.pdf): Swap the contained values of `*this` and `rhs` with a temporary storage. If an exception is thrown, each of `*this` and `rhs` is in a valid state with unspecified value.

> Can you explain why design is not value semantic oriented?

See section 4.1 of the paper. 4.3.1 also compared the design with "dyno", which is also based on value semantics.

**Comment by kelbon** [comment]
> No, it's not. None of the standard types have strong exception safety guarantee on `swap`. See the wording in 5.3.3.4, [P0957R6](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p0957r6.pdf): Swap the contained values of `*this` and `rhs` with a temporary storage. If an exception is thrown, each of `*this` and `rhs` is in a valid state with unspecified value.

Im about this :
`Effects: As if by proxy(rhs).swap(*this). No effects if an exception is thrown` , it seems like swap has strong exception guarantee

**Comment by mingxwa** [comment]
> Im about this :
> Effects: As if by proxy(rhs).swap(*this). No effects if an exception is thrown , it seems like swap has strong exception guarantee

This a valid concern... I need to revise the wording. Thank you for the comment!

**Comment by kelbon** [comment]
> See section 4.1 of the paper. 4.3.1 also compared the design with "dyno", which is also based on value semantics.

Your point mostly about allocator customization, but my solution uses allocator and it can be customized. Ye, i think we must divide allocator and memory resource in standard, where memory resource have less requirements and not typed. It will be usefull in std::pmr, C++20 coroutine support, and type erasing. when i implementing a coroutines(on my github too) and AnyAny i meet this problem.
But value semantic good for code understanding, SOO -like optimizations etc

**Comment by mingxwa** [comment]
> Your point mostly about allocator customization

Yeah. It's very important for performance. You can try to implement the "simple factory" requirements illustrated in 3.4.2 with your library and see the generated assembly code. The demo code of proxy is available here: https://github.com/mingxwa/my-stl/blob/master/demo/p0957/drawable.cc

`proxy` does not have anything to do with `pmr`, it only requires "pointers", basically any pointers with or without lifetime management. You can also use `std::shared_ptr` or some `gc_ptr` if necessary.

> But value semantic good for code understanding, SOO -like optimizations etc

The implementation of `proxy` has no knowledge of SOO or allocators. But these features could also be easily implemented with little code if needed (see the implementation of `make_proxy`, which applies SOO).
